language: node_js
node_js:
  - node # latest stable
  - 10
  - 8
cache:
  directories:
    - node_modules
install:
  - npm prune
  - npm install
script:
  - npm run lint
  - npm install --global resume-cli
  - npm install --global jsonresume-theme-rocketspacer
  - resume export --force --theme rocketspacer public/index.html
deploy:
  # https://docs.travis-ci.com/user/deployment/pages
  provider: pages
  skip-cleanup: true
  keep-history: true
  github-token: $GITHUB_TOKEN
  local-dir: public
  on:
    branch: master
    node: 8
